# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := GYP
LOCAL_MODULE := third_party_WebKit_Source_bindings_modules_v8_bindings_modules_v8_generated_init_partial_gyp
LOCAL_MODULE_STEM := bindings_modules_v8_generated_init_partial
LOCAL_MODULE_SUFFIX := .stamp
LOCAL_MODULE_TARGET_ARCH := $(TARGET_$(GYP_VAR_PREFIX)ARCH)
LOCAL_SDK_VERSION := 21
gyp_intermediate_dir := $(call local-intermediates-dir,,$(GYP_VAR_PREFIX))
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared,,,$(GYP_VAR_PREFIX))

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES :=

### Rules for action "generate_bindings_modules_v8_init_partial":
$(gyp_shared_intermediate_dir)/blink/bindings/modules/v8/initPartialInterfacesInModules.cpp: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/blink/bindings/modules/v8/initPartialInterfacesInModules.cpp: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/blink/bindings/modules/v8/initPartialInterfacesInModules.cpp: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/blink/bindings/modules/v8/initPartialInterfacesInModules.cpp: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/blink/bindings/modules/v8/initPartialInterfacesInModules.cpp: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/blink/bindings/modules/v8/initPartialInterfacesInModules.cpp: $(LOCAL_PATH)/third_party/WebKit/Source/bindings/scripts/generate_init_partial_interfaces.py $(LOCAL_PATH)/third_party/WebKit/Source/bindings/modules/v8/core_idl_with_modules_dependency_files_list.tmp $(gyp_shared_intermediate_dir)/blink/bindings/modules/InterfacesInfoOverall.pickle $(GYP_TARGET_DEPENDENCIES)
	@echo "Gyp action: third_party_WebKit_Source_bindings_modules_v8_generated_gyp_bindings_modules_v8_generated_init_partial_target_generate_bindings_modules_v8_init_partial ($@)"
	$(hide)cd $(gyp_local_path)/third_party/WebKit/Source/bindings/modules/v8; mkdir -p $(gyp_shared_intermediate_dir)/blink/bindings/modules/v8; python ../../scripts/generate_init_partial_interfaces.py --idl-files-list core_idl_with_modules_dependency_files_list.tmp --output "$(gyp_shared_intermediate_dir)/blink/bindings/modules/v8/initPartialInterfacesInModules.cpp" --write-file-only-if-changed 0



GYP_GENERATED_OUTPUTS := \
	$(gyp_shared_intermediate_dir)/blink/bindings/modules/v8/initPartialInterfacesInModules.cpp

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

### Rules for final target.
### Set directly by aosp_build_settings.
LOCAL_CLANG := false
LOCAL_NDK_STL_VARIANT := stlport_static

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: third_party_WebKit_Source_bindings_modules_v8_bindings_modules_v8_generated_init_partial_gyp

# Alias gyp target name.
.PHONY: bindings_modules_v8_generated_init_partial
bindings_modules_v8_generated_init_partial: third_party_WebKit_Source_bindings_modules_v8_bindings_modules_v8_generated_init_partial_gyp

LOCAL_MODULE_PATH := $(PRODUCT_OUT)/gyp_stamp
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_2ND_ARCH_VAR_PREFIX := $(GYP_VAR_PREFIX)

include $(BUILD_SYSTEM)/base_rules.mk

$(LOCAL_BUILT_MODULE): $(LOCAL_ADDITIONAL_DEPENDENCIES)
	$(hide) echo "Gyp timestamp: $@"
	$(hide) mkdir -p $(dir $@)
	$(hide) touch $@

LOCAL_2ND_ARCH_VAR_PREFIX :=
